"""Minimal type stubs for xbmcgui."""
from typing import Any, Iterable

NOTIFICATION_INFO: str
NOTIFICATION_WARNING: str
NOTIFICATION_ERROR: str


class ListItem:
    def __init__(self, label: str = ..., label2: str = ..., path: str = ...) -> None: ...
    def setLabel(self, label: str) -> None: ...
    def setLabel2(self, label: str) -> None: ...
    def setPath(self, path: str) -> None: ...
    def setArt(self, art: dict[str, str]) -> None: ...
    def setInfo(self, type: str, infoLabels: dict[str, Any]) -> None: ...
    def setProperty(self, key: str, value: str) -> None: ...
    def getProperty(self, key: str) -> str: ...
    def addContextMenuItems(self, items: Iterable[tuple[str, str]], replaceItems: bool = ...) -> None: ...
    def setMimeType(self, mimetype: str) -> None: ...
    def setContentLookup(self, enable: bool) -> None: ...


class Window:
    def __init__(self, existingWindowId: int = ...) -> None: ...
    def getProperty(self, key: str) -> str: ...
    def setProperty(self, key: str, value: str) -> None: ...
    def clearProperty(self, key: str) -> None: ...
    def show(self) -> None: ...
    def close(self) -> None: ...
    def addControl(self, control: Any) -> None: ...
    def removeControl(self, control: Any) -> None: ...


class WindowDialog(Window):
    pass


class ControlImage:
    def __init__(self, x: int, y: int, width: int, height: int, filename: str,
                 colorDiffuse: str = ..., aspectRatio: int = ...) -> None: ...
    def setImage(self, filename: str) -> None: ...


class ControlLabel:
    def __init__(self, x: int, y: int, width: int, height: int, label: str,
                 font: str = ..., textColor: str = ..., disabledColor: str = ...,
                 alignment: int = ..., hasPath: bool = ..., angle: int = ...) -> None: ...
    def setLabel(self, label: str) -> None: ...
    def setPosition(self, x: int, y: int) -> None: ...


class Dialog:
    def __init__(self) -> None: ...
    def ok(self, heading: str, message: str) -> bool: ...
    def yesno(self, heading: str, message: str, nolabel: str = ..., yeslabel: str = ...) -> bool: ...
    def notification(self, heading: str, message: str, icon: str = ...,
                     time: int = ..., sound: bool = ...) -> None: ...
    def numeric(self, type: int, heading: str, defaultt: str = ...) -> str: ...
    def input(self, heading: str, defaultt: str = ..., type: int = ...) -> str: ...
    def select(self, heading: str, list: Iterable[str], autoclose: int = ...,
               preselect: int = ..., useDetails: bool = ...) -> int: ...


class DialogProgress:
    def create(self, heading: str, message: str = ...) -> None: ...
    def update(self, percent: int, message: str = ...) -> None: ...
    def close(self) -> None: ...
    def iscanceled(self) -> bool: ...
