"""Minimal type stubs for the xbmc module so mypy --strict can check
resources/lib/* without a real Kodi install.
"""
from typing import Any

LOGDEBUG: int
LOGINFO: int
LOGNOTICE: int
LOGWARNING: int
LOGERROR: int
LOGFATAL: int

PLAYLIST_VIDEO: int
PLAYLIST_MUSIC: int


def log(msg: str, level: int = ...) -> None: ...
def executebuiltin(cmd: str, wait: bool = ...) -> None: ...
def getGlobalIdleTime() -> int: ...
def sleep(ms: int) -> None: ...
def getInfoLabel(label: str) -> str: ...


class Monitor:
    def abortRequested(self) -> bool: ...
    def waitForAbort(self, timeout: float = ...) -> bool: ...


class Player:
    def __init__(self) -> None: ...
    def play(self, item: Any = ..., listitem: Any = ..., windowed: bool = ..., startpos: int = ...) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def isPlaying(self) -> bool: ...
    def isPlayingVideo(self) -> bool: ...
    def isPlayingAudio(self) -> bool: ...
    def getPlayingFile(self) -> str: ...
    def onPlayBackStarted(self) -> None: ...
    def onAVStarted(self) -> None: ...
    def onPlayBackEnded(self) -> None: ...
    def onPlayBackStopped(self) -> None: ...
    def onPlayBackError(self) -> None: ...


class PlayList:
    def __init__(self, playlist_id: int) -> None: ...
    def add(self, url: str, listitem: Any = ..., index: int = ...) -> None: ...
    def clear(self) -> None: ...
    def getposition(self) -> int: ...
    def size(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
