"""Minimal type stubs for xbmcvfs."""
from typing import Any


def translatePath(path: str) -> str: ...
def exists(path: str) -> bool: ...
def mkdir(path: str) -> bool: ...
def mkdirs(path: str) -> bool: ...
def delete(path: str) -> bool: ...
def rename(src: str, dst: str) -> bool: ...
def copy(src: str, dst: str) -> bool: ...


class File:
    def __init__(self, path: str, mode: str = ...) -> None: ...
    def read(self, size: int = ...) -> str: ...
    def readBytes(self, size: int = ...) -> bytes: ...
    def write(self, data: Any) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> "File": ...
    def __exit__(self, *args: Any) -> None: ...
