"""Minimal type stubs for xbmcaddon."""


class Addon:
    def __init__(self, id: str = ...) -> None: ...
    def getAddonInfo(self, key: str) -> str: ...
    def getSetting(self, id: str) -> str: ...
    def getSettingBool(self, id: str) -> bool: ...
    def getSettingInt(self, id: str) -> int: ...
    def getSettingString(self, id: str) -> str: ...
    def setSetting(self, id: str, value: str) -> None: ...
    def setSettingBool(self, id: str, value: bool) -> None: ...
    def setSettingInt(self, id: str, value: int) -> None: ...
    def setSettingString(self, id: str, value: str) -> None: ...
    def getLocalizedString(self, id: int) -> str: ...
