"""Minimal type stubs for xbmcplugin."""
from typing import Any

SORT_METHOD_NONE: int
SORT_METHOD_UNSORTED: int
SORT_METHOD_LABEL: int
SORT_METHOD_DATE: int


def addDirectoryItem(handle: int, url: str, listitem: Any,
                     isFolder: bool = ..., totalItems: int = ...) -> bool: ...
def addDirectoryItems(handle: int, items: list[tuple[str, Any, bool]],
                      totalItems: int = ...) -> bool: ...
def endOfDirectory(handle: int, succeeded: bool = ..., updateListing: bool = ...,
                   cacheToDisc: bool = ...) -> None: ...
def setContent(handle: int, content: str) -> None: ...
def setPluginCategory(handle: int, category: str) -> None: ...
def setResolvedUrl(handle: int, succeeded: bool, listitem: Any) -> None: ...
def addSortMethod(handle: int, sortMethod: int, label2Mask: str = ...) -> None: ...
